In [2]:
import numpy as np
#import pandas
#from sklearn import model_selection
#from sklearn.linear_model import LogisticRegression
#import pickle

#def neuralnetwork():
    #Input array
X=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])

    #Output
y=np.array([[1],[1],[0]])

    #Sigmoid Function
def sigmoid (x):
    return 1/(1 + np.exp(-x))

    #Derivative of Sigmoid Function
def derivatives_sigmoid(x):
    return x * (1 - x)

    #Variable initialization
epoch=500000 #Setting training iterations
lr=0.1 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

    #weight and bias initialization
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))

for i in range(epoch):

    #Forward Propogation
    hidden_layer_input1=np.dot(X,wh)
    hidden_layer_input=hidden_layer_input1 + bh
    hiddenlayer_activations = sigmoid(hidden_layer_input)
    output_layer_input1=np.dot(hiddenlayer_activations,wout)
    output_layer_input= output_layer_input1+ bout
    output = sigmoid(output_layer_input)

    #Backpropagation
    E = y-output
    slope_output_layer = derivatives_sigmoid(output)
    slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
    d_output = E * slope_output_layer
    Error_at_hidden_layer = d_output.dot(wout.T)
    d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
    wout += hiddenlayer_activations.T.dot(d_output) *lr
    bout += np.sum(d_output, axis=0,keepdims=True) *lr
    wh += X.T.dot(d_hiddenlayer) *lr
    bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *lr

print output



[[ 0.99839495]
 [ 0.99753652]
 [ 0.00288053]]


In [3]:
import numpy as np

In [4]:
X=np.array([[1,0,1,0],[1,0,1,1],[1,1,1,1]])
y=np.array([[1],[0],[1]])

In [5]:
#define sigmoid function
def sigmoid(x):
    return 1/(1+np.exp(-x))

#define derivative of sigmoid

def dvsigmoid(x):
    return x*(1-x)


In [6]:
#variables initialization

epoch = 100000 #number of itteration
lr=.1
input_layer_neuron = X.shape[1]   #number of features in data set
hidden_layer_neuron= 10
output_neuron = 1

In [7]:
# weights and bias initialization
wh=np.random.uniform(size=(input_layer_neuron,hidden_layer_neuron))
bh=np.random.uniform(size=(1,hidden_layer_neuron))
wout=np.random.uniform(size=(hidden_layer_neuron,output_neuron))
bout=np.random.uniform(size=(1,output_neuron))

In [8]:
for i in range(epoch):
    #forward propogation
    hidden_layer_input1=np.dot(X,wh)
    hidden_layer_input=hidden_layer_input1+bh
    hidden_layer_activation=sigmoid(hidden_layer_input)
    output_layer_input1=np.dot(hidden_layer_activation,wout)
    output_layer_input=output_layer_input1+bout
    output = sigmoid(output_layer_input)
    
    
    #backward propogation
    
    E=y-output
    slope_of_output = dvsigmoid(output)
    slope_hidden_layer = dvsigmoid(hidden_layer_activation)
    d_output = E*slope_of_output
    Error_at_hidden_layer = d_output.dot(wout.T)
    d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
    #d_hiddenlayer= Error_at_hiddenlayer*slope_hidden_layer
    wout += hidden_layer_activation.T.dot(d_output)*lr
    bout +=np.sum(d_output,axis=0,keepdims=True)*lr
    wh +=X.T.dot(d_hiddenlayer)*lr
    bh +=np.sum(d_hiddenlayer,axis=0, keepdims=True)*lr
    
    
print output
    

[[ 0.99468945]
 [ 0.00769922]
 [ 0.99451912]]


In [9]:
import pandas as pd


In [10]:
raw_data = {"first_name":["janmejay", "arun","deepak","pankaj","govind","rohit"],"last_name":["singh",'singh','mishra','singh','gupta','kapoor'],'age':[28,32,27,29,24,27]}
df = pd.DataFrame(raw_data,columns=['first_name','last_name','age'])

In [11]:
a=np.array(df)

a

for i in a:
    print i
    

['janmejay' 'singh' 28]
['arun' 'singh' 32]
['deepak' 'mishra' 27]
['pankaj' 'singh' 29]
['govind' 'gupta' 24]
['rohit' 'kapoor' 27]


In [12]:
a.shape[1]

3

In [13]:
df[0:1]

first_name last_name  age
0   janmejay     singh   28

In [14]:
raw_data

{'age': [28, 32, 27, 29, 24, 27],
 'first_name': ['janmejay', 'arun', 'deepak', 'pankaj', 'govind', 'rohit'],
 'last_name': ['singh', 'singh', 'mishra', 'singh', 'gupta', 'kapoor']}

In [15]:
import numpy as np


In [16]:
def sigmoid(x):
    return 1/(1+np.exp(-x))
def dersigmoid(x):
    return x*(1-x)

In [17]:
    #Input array
X=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])

    #Output
y=np.array([[1],[1],[0]])

In [18]:
#initializing variable
epoch = 10000  # number of itterations
lr = .1
input_neuron =X.shape[1]
hidden_layer_neuron =3
output_neuron = 1






In [19]:
#weights and bais initialization
wh= np.random.uniform(size=(input_neuron,hidden_layer_neuron))
bh=np.random.uniform(size=(1,hidden_layer_neuron))
wout= np.random.uniform(size=(hidden_layer_neuron,output_neuron))
bout= np.random.uniform(size=(1,output_neuron))


In [20]:
for i in range(epoch):
    #forward propogation
    
    hidden_layer_input1=np.dot(X,wh)
    hidden_layer_input=hidden_layer_input1+bh
    hidden_layer_activation=sigmoid(hidden_layer_input)
    output_layer_input1= np.dot(hidden_layer_activation,wout)
    output_layer_input = output_layer_input1+bout
    output= sigmoid(output_layer_input)
    
    
    #backward propagation
    
    E=y-output
    slope_of_output = dersigmoid(output)
    slope_of_hiddenlayer=dersigmoid(hidden_layer_activation)
    d_output = slope_of_output*E
    error_at_hiddenlayer = d_output.dot(wout.T)
    d_hiddenlayer = error_at_hiddenlayer*slope_of_hiddenlayer
    wout+=hidden_layer_activation.T.dot(d_output)*lr
    bout+=np.sum(d_output,axis=0,keepdims=True)*lr
    wh +=X.T.dot(d_hiddenlayer)*lr
    bh+=np.sum(d_hiddenlayer,axis=0,keepdims=True)*lr
    
output
    
    

array([[ 0.98918636],
       [ 0.98256188],
       [ 0.02323246]])

In [21]:
for i in range(epoch):
    #forwad propogation
    hidden_layer_input1=np.dot(X,wh)
    hidden_layer_input=hidden_layer_input1+bh
    hidden_layer_activation = sigmoid(hidden_layer_input)
    output_layer_input1 = np.dot(hidden_layer_activation,wout)
    output_layer_input = output_layer_input1+bout
    output= sigmoid(output_layer_input)
    output
    
    
    #backward propogation
    E= y-output
    slope_of_ouput = dersigmoid(output)
    slope_of_hiddenlayer = dersigmoid(hidden_layer_activation)
    d_output = slope_of_output*E
    error_at_hiddenlayer=d_output.dot(wout.T)
    d_hiddenlayer = error_at_hiddenlayer*slope_of_hiddenlayer
    wout +=hidden_layer_activation.T.dot(d_output)*lr
    bout +=np.sum(d_output,axis=0,keepdims=True)*lr
    wh +=X.T.dot(d_hiddenlayer)*lr
    bh +=np.sum(d_hiddenlayer,axis=0,keepdims=True)*lr
output    
    

array([[ 0.9931998 ],
       [ 0.98896481],
       [ 0.01468949]])